[package]
name = "rust"
version = "0.1.0"
authors = ["Administrator"]
edition = "2018"

[dependencies]
actix-web = "0.7.18"
mysql = "15.0.0"

[[bin]]
name = "server"
path = "src/server.rs"
[[bin]]
name = "client"
path = "src/client.rs"